version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: midascen_app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - midascen_net

  nginx:
    image: nginx:alpine
    container_name: midascen_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - midascen_net

  db:
    image: postgres:16
    container_name: midascen_db
    restart: always
    environment:
      POSTGRES_DB: midascendb
      POSTGRES_USER: midascen
      POSTGRES_PASSWORD: 12345678
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - midascen_net

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: midascen_queue
    command: php artisan queue:work
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - midascen_net

volumes:
  pgdata:

networks:
  midascen_net: